version: "3.8"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/passwd:/etc/passwd:cached
      - /etc/group:/etc/group:cached
      - ./bot:/bot:cached
